### ISSUE TITLE
[Roadmap] Version v0.1.0

### ISSUE THREAD

**Issue by kunish** [daeuniverse/daed#10]
# Overview

As we continue to develop our project, it is important to have a clear roadmap towards version **v1.0.0**. This will help us stay focused on our goals and ensure that we are making progress towards a stable and reliable first release.

# Goals

Our goals for version **v0.1.0** are as follows:

- [x] Enhance documentation and user guides
- [x] Integrate with dae-wing by bundle it within daed this project itself
- [x] Under **simple mode**, make sure a user, who has very limited knowledge about this project, can run this thing without having too much headache.
- [x] Under **advanced mode**, make sure every resource required to run a proxy service is exposed to user completely
- [x] Resolve all known bugs and issues
- [x] Determine release cycle
- [x] Utilize full-tested and stable CI workflows 

# Feedback
We welcome any feedback or suggestions on the proposed goals. Please feel free to leave your comments and ideas below.

Thank you for your support and contribution to our project!

**Comment by kunish** [comment]
**daed v0.1.0** is finally here! 🚀 

https://github.com/daeuniverse/daed/releases/tag/v0.1.0

This couldn't be possible without our community members and contributors, thank you!
