### ISSUE TITLE
[Bug Report] pname(qbittorrent) 非 must 出站会导致 qbittorrent 无法连接 tracker

### ISSUE THREAD

**Issue by sommio** [daeuniverse/daed#429]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

pname(qbittorrent) direct 会导致 qbittorrent 无法连接 tracker

```bash
# DNS配置
ipversion_prefer: 4
upstream {
  dnspub: 'udp://119.29.29.29:53'
  cloudflare: 'tcp://1.1.1.1:53'
}
routing {
  request {
    qname(suffix: zhimg.com) -> dnspub
    qname(geosite:category-social-media-cn) -> cloudflare
    qname(geosite:cn) -> dnspub
    fallback: cloudflare
  }
}
```

```bash
# cat /etc/resolv.conf
nameserver 119.29.29.29
nameserver 223.5.5.5
nameserver 223.6.6.6
nameserver 127.0.0.1
```

```bash
# 无法连接 tracker
pname(NetworkManager) -> direct
dip(224.0.0.0/3, 'ff00::/8', geoip:private) -> direct
pname(qbittorrent-nox) -> direct
pname(qbittorrent) -> direct
```

```bash
# 正常工作
pname(NetworkManager) -> direct
dip(224.0.0.0/3, 'ff00::/8', geoip:private) -> direct
pname(qbittorrent-nox) -> must_direct
pname(qbittorrent) -> must_direct
```

```bash
# 另一个正常工作路由，但似乎没有按期望全局走 dae dns
dip(geoip:private) -> direct
pname(NetworkManager, systemd-resolved) -> direct
pname(qbittorrent-nox) -> must_direct
pname(qbittorrent) -> must_direct
```
![截图 2024-04-13 00-06-44](https://github.com/daeuniverse/daed/assets/64189793/ee33fadd-4051-4b6d-8b5a-c8cf792c2d3b)

### Expected Behavior

与 must_direct 一样可以正常链接 tracker

![截图 2024-04-13 00-15-15](https://github.com/daeuniverse/daed/assets/64189793/c7a6ed9e-e8ad-45d9-9227-81e855dd3fb2)

### Environment

- **Daed version**: daed v0.4.0rc1
- **OS**: Arch Linux
- **Kernel**: 6.6.25-2-cachyos-lts-lto
- **Others**: daed-bin-x64-v3 from archlinuxcn

### Anything else?

使用其它非 must 出站也会重现此问题，虽无法连接 tracker 但均可上传

```bash
pname(NetworkManager) -> direct
dip(224.0.0.0/3, 'ff00::/8', geoip:private) -> direct
pname(qbittorrent-nox) -> must_direct
pname(qbittorrent) -> must_direct
```
![截图 2024-04-13 00-23-12](https://github.com/daeuniverse/daed/assets/64189793/77ad949e-4e93-436f-bf69-dcc4fe8af999)
![截图 2024-04-13 00-29-30](https://github.com/daeuniverse/daed/assets/64189793/a64867a1-8b5a-4d60-bdf5-282b65e44e99)

**Comment by mzz2017** [comment]
@sommio 这个会导致 dns 查询使用 cloudflare，但是由于 pname 是 qbittorrent，dns 会使用 direct，建议 routing 前面对 1.1.1.1 设置 proxy

**Comment by sommio** [comment]
感谢 mzz，问题解决了
```bash
pname(NetworkManager) -> direct
dip(224.0.0.0/3, 'ff00::/8', geoip:private) -> direct
dip(1.1.1.1) -> proxy
pname(qbittorrent-nox, qbittorrent) -> direct
```
